 # Generated by Django 6.1 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], default='new', max_length=10, verbose_name='Состояние'),
        ),
    ]
