# Generated by Django 6.1 on 2026-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'контактная информация',
                'verbose_name_plural': 'контактная информация',
            },
        ),
    ]
